package Telephone.Cell;

/**
* Cell/StationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Telephone.idl
* 17 ��� 2022 �. 16:16:49 MSK
*/


/*  ? ! �!! � !  � � � U  U  !! � !  Q Q */
public final class StationHolder implements org.omg.CORBA.portable.Streamable
{
  public Station value = null;

  public StationHolder ()
  {
  }

  public StationHolder (Station initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StationHelper.type ();
  }

}
