package Telephone.Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Telephone.idl
* 17 ìàÿ 2022 ã. 16:16:49 MSK
*/


/*  ? ! µ!! µ !  ± ° · U  U  !! ° !  Q Q */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
