package Telephone.Cell;

/**
* Cell/TubeCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Telephone.idl
* 17 ��� 2022 �. 16:16:49 MSK
*/


/*  ? ! �!! � !  U �! �!  U V U  !9 � U  � !!!S � T Q */
public final class TubeCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public TubeCallback value = null;

  public TubeCallbackHolder ()
  {
  }

  public TubeCallbackHolder (TubeCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TubeCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TubeCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TubeCallbackHelper.type ();
  }

}
