package Telephone.App;


/**
* App/StationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Telephone.idl
* 17 ��� 2022 �. 16:16:49 MSK
*/


/*  ? ! �!! � !  � � � U  U  !! � !  Q Q */
public abstract class StationPOA extends org.omg.PortableServer.Servant
 implements StationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("register", new java.lang.Integer (0));
    _methods.put ("sendSMS", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /*  ? �!  U �! �!  U V U  !9 � U  � !!!S � T Q  Q! W U �!
 � U  �!!
 !!!9 � T!S TubeCallback */
       case 0:  // App/Station/register
       {
         TubeCallback objRef = TubeCallbackHelper.read (in);
         String phoneNum = in.read_string ();
         int $result = (int)0;
         $result = this.register (objRef, phoneNum);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  /*  [! W! �  Q!!
 ! U U �!0 �  Q � message  U!   U X �! � fromNum  T   U X �!!S toNum */
       case 1:  // App/Station/sendSMS
       {
         String fromNum = in.read_string ();
         String toNum = in.read_string ();
         String message = in.read_string ();
         int $result = (int)0;
         $result = this.sendSMS (fromNum, toNum, message);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:App/Station:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Station _this() 
  {
    return StationHelper.narrow(
    super._this_object());
  }

  public Station _this(org.omg.CORBA.ORB orb) 
  {
    return StationHelper.narrow(
    super._this_object(orb));
  }


} // class StationPOA
