package Telephone.App;


/**
* App/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Telephone.idl
* 17 ��� 2022 �. 16:16:49 MSK
*/


/*  ? ! �!! � !  � � � U  U  !! � !  Q Q */
public interface StationOperations 
{

  /*  ? �!  U �! �!  U V U  !9 � U  � !!!S � T Q  Q! W U �!
 � U  �!!
 !!!9 � T!S TubeCallback */
  int register (TubeCallback objRef, String phoneNum);

  /*  [! W! �  Q!!
 ! U U �!0 �  Q � message  U!   U X �! � fromNum  T   U X �!!S toNum */
  int sendSMS (String fromNum, String toNum, String message);
} // interface StationOperations
